import React, { createContext, useState } from 'react'

export const Store = createContext()

const DataStorage = (props) => {
    const [Data] = useState([
      {
        id:1,
        genre: 'Bollywood',
        ref: 'https://www.bollywoodlife.com/videos/kiara-advani-birthday-journey-from-child-model-to-successful-bollywood-actress-2529733/',
        image: 'https://st1.bollywoodlife.com/wp-content/uploads/2023/07/00000021-6.jpeg?impolicy=Medium_Widthonly&w=420',
        heading: 'Kiara Advani Birthday: Journey From Child Model to Successful Bollywood Actress',
        subheading: 'Kiara Advani\'s philanthropic efforts have garnered attention. She actively participates in various charitable initiatives and supports causes close to her heart. She started as a child model, Kiara\'s path to Bollywood success has been nothing short of extraordinary.',
        content: 'Starting as a child model, Kiara\'s path to Bollywood success has been nothing short of extraordinary. The young Kiara, born as Alia Advani but changed her name to Kiara Advani, as suggested by Salman Khan. She initially ventured into the modeling world and quickly gained recognition for her striking looks and charming presence on the runway. Gradually, her passion for performing arts led her to explore acting opportunities. Kiara\'s Bollywood debut came with the 2014 film "Fugly," which received a mixed response. However, it was her breakthrough role as Sakshi Dhoni, the wife of Indian cricket legend MS Dhoni, in the biopic "M.S. Dhoni: The Untold Story" (2016) that catapulted her to stardom. Her convincing portrayal earned her accolades and marked a turning point in her career. Following her successful debut, Kiara ventured into various genres, proving her versatility as an actress. Her impactful performances in movies like "Machine," "Lust Stories," and "Kabir Singh" further solidified her position as one of Bollywood\'s sought-after leading ladies. Kiara\'s dedication to her craft, combined with her radiant charm and endearing personality, has earned her a massive fan following. Her fashion sense and glamorous appearances on red carpets have also made her a style icon. Her incredible transformation from a young model to a versatile and successful actress stands as an inspiration to aspiring talents, and her fans eagerly await her future endeavors, confident that she will continue to leave an indelible mark in the realm of Indian cinema.',
        date: 'July 31, 2023'
      },
      {
        id:2,
        genre: 'Bollywood',
        ref: 'https://www.bollywoodlife.com/videos/omg-2-controversy-akshay-kumars-lord-shiva-character-to-be-changed-2529533/',
        image: 'https://st1.bollywoodlife.com/wp-content/uploads/2023/07/00000011-33.jpeg?impolicy=Medium_Widthonly&w=420',
        heading: 'OMG 2 Controversy: Akshay Kumar\'s Lord Shiva character to be changed?',
        subheading: 'In a sudden shift of events, the hotly anticipated "OMG - Oh My God!" sequel gets involved in a contentious debate. The Central Board of Film Certification (CBFC) has suggested changing Akshay Kumar\'s iconic portrayal of Lord Shiva in "OMG 2."',
        content: 'OMG 2 Controversy: In a surprising turn of events, the highly anticipated sequel to the blockbuster "OMG - Oh My God!" is embroiled in a heated controversy. Reports suggest that the Central Board of Film Certification (CBFC) has recommended altering Akshay Kumar\'s iconic portrayal of Lord Shiva in "OMG 2." The original film, released several years ago, garnered immense praise for its thought-provoking storyline and Akshay Kumar\'s remarkable performance as the modern-day Lord Shiva. However, with "OMG 2" in the works, the CBFC\'s suggestion to replace Lord Shiva\'s character with a different mythological figure has raised eyebrows among fans and cinephiles alike. The CBFC\'s decision has sparked debates within the film industry and among audiences about artistic freedom and the portrayal of religious figures on the big screen. Some argue that altering Lord Shiva\'s character could dilute the essence of the film\'s message, which focused on questioning religious practices and embracing spirituality beyond conventions. As the controversy gains momentum, the production team of "OMG 2" has remained tight-lipped about the proposed changes, leaving fans eagerly awaiting an official statement. The film\'s director, Anees Bazmee, has hinted at a few surprises in the storyline, fueling speculation further. For now, the fate of Akshay Kumar\'s portrayal of Lord Shiva and the potential introduction of a new character in "OMG 2" remains uncertain. As discussions continue to unfold, the movie\'s release date could face delays until the matter is resolved with the CBFC.',
        date: 'July 31, 2023'
      },
      {
        id:3,
        genre: 'Bollywood',
        ref: 'https://www.bollywoodlife.com/news-gossip/kgf-3-yash-puts-a-condition-to-be-a-part-of-prashanth-neel-directorial-entertainment-news-stst-2530226/',
        image: 'https://www.bollywoodlife.com/news-gossip/kgf-3-yash-puts-a-condition-to-be-a-part-of-prashanth-neel-directorial-entertainment-news-stst-2530226/',
        heading: 'KGF 3: Yash puts a condition to be a part of Prashanth Neel directorial',
        subheading: 'Kannada actor Yash has earned global fandom through his performance in director Prashanth Neel’s KGF and KGF 2. After a dream, box office run in India, this year on July 14, both films were screened across theaters in Japan, which received the same amount of love as the Indian audience. To add cherry on top of the cake, the makers have confirmed that KGF 3 is already underway. Amidst all this, another interesting revelation surrounding Yash has come to the fore. Reportedly, Yash will be part of KGF\'s third segment only under one condition.',
        date: 'July 31, 2023'
      },
      {
        id: 4,
        genre: 'Bollywood',
        ref: 'https://www.bollywoodlife.com/news-gossip/why-hema-malini-doesnt-stays-with-dharmendra-actress-broke-her-silence-on-this-checkout-2529619/',
        image: 'https://st1.bollywoodlife.com/wp-content/uploads/2023/07/why-Hema-malini-dont-stay-with-Dharmendra.jpg?impolicy=Medium_Widthonly&w=1280&h=900',
        heading: 'Why Hema Malini does not stay with Dharmendra? Actress breaks her silence',
        subheading: 'Hema Malini doesn\'t need any introduction, but still, people ask about her relationship with Dharmendra and why she doesn\'t live with him despite being married. Recently she opened up on this matter.',
        content: 'Dharmendra is currently in the spotlight because of a kissing scene he had with Shabana Azmi, who primarily lives with his ex-wife Prakash Kaur and their children. His second wife, Hema Malini, discussed her relationship with him just a few days ago and explained why, despite their marriage, she does not live with him. Although Hema Malini is content in her marriage to Dharmendra, her parents did not initially support their daughter\'s love for the \'Sholay\' actor because he was previously married to Prakash Kaur. Hema Malini had no complaints about Dharmendra, who remarried Dream Girl without divorcing Prakash Kaur, despite their 43-year marriage. At the moment, Dharmendra resides with his ex-wife and her family. ',
        date: 'July 31, 2023',
      },
      {
        id: 5,
        genre: 'Bollywood',
        ref: 'https://www.bollywoodlife.com/news-gossip/gadar-2-sunny-deol-ameesha-patels-film-will-have-not-one-but-two-antagonists-deets-inside-entertainment-news-stst-2529918/',
        image: 'https://www.bollywoodlife.com/news-gossip/gadar-2-sunny-deol-ameesha-patels-film-will-have-not-one-but-two-antagonists-deets-inside-entertainment-news-stst-2529918/',
        heading: 'Gadar 2: Sunny Deol, Ameesha Patel\'s film will have not one but two antagonists; deets inside',
        subheading: 'Rohit Choudhary revealed that after Gadar 2 director Anil Sharma was left impressed by his hard work, the filmmaker extended his screen time in the film.',
        content: 'Gadar: The Katha Continues or Gadar 2, starring Sunny Deol and Ameesha Patel is ready to hit the theatres on August 11. The film’s much-anticipated trailer promises high-octane action. Also, this time, the story will focus on the father-son equation, between Sunny Deol’s Tara Singh and actor Utkarsh Sharma’s Charanjeet. Earlier, it was reported that Manish Wadhwa, who portrayed the role of Genetal Qadir in Shah Rukh Khan’s Pathaan, will be the prime antagonist in Gadar 2. In what comes as an interesting addition, it is now unveiled that Gadar 2 will have another villain. And he is Rohit Choudhary. ',
        date: 'July 31, 2023',
      },
      {
        id: 6,
        genre: 'Bollywood',
        ref: 'https://www.bollywoodlife.com/news-gossip/rocky-aur-rani-kii-prem-kahaani-alia-bhatt-pens-thank-you-note-for-fans-following-positive-response-eternally-grateful-entertainment-news-stst-2529677/',
        image: 'https://www.bollywoodlife.com/news-gossip/rocky-aur-rani-kii-prem-kahaani-alia-bhatt-pens-thank-you-note-for-fans-following-positive-response-eternally-grateful-entertainment-news-stst-2529677/',
        heading: 'Rocky Aur Rani Kii Prem Kahaani: Alia Bhatt pens thank you note for fans following positive response, ‘eternally grateful’',
        subheading: 'In the picture, Ranveer donned a simple tee that he teamed up with a black cap and a silver chain.',
        content: 'Ranveer Singh and Alia Bhatt are currently on cloud nine, with their latest film Rocky Aur Rani Kii Prem Kahaani scoring big in the theatres. The Karan Johar directorial witnessed a good box office run in its opening weekend, collecting approximately Rs 87 crore worldwide. Although the film opened to mixed reviews from critics, fans seem to have poured all their love into the romantic comedy. Elated at the overwhelming response, Alia Bhatt penned a heartwarming note on Instagram saying “eternally grateful” for the abundance of love. Along with the write-up, she also dropped a picture with her RARKPK co-star Ranveer and Karan Johar.',
        date: 'July 31, 2023',
      },
      {
        id: 7,
        genre: 'Bollywood',
        ref: 'https://www.bollywoodlife.com/news-gossip/sobhita-dhulipala-ignores-ishaan-khattar-on-the-ramp-netizens-point-out-lack-of-chemistry-entertainment-news-2529334/',
        image: 'https://www.bollywoodlife.com/news-gossip/sobhita-dhulipala-ignores-ishaan-khattar-on-the-ramp-netizens-point-out-lack-of-chemistry-entertainment-news-2529334/',
        heading: 'Sobhita Dhulipala \'ignores\' Ishaan Khattar on the ramp; netizens point out lack of chemistry',
        subheading: 'Sobhita Dhulipala royally ignores Ishaan Khattar at the ramp walk; netizens are going bonkers with her expression and is calling the actor a school kid infront of the Made In Heaven 2 actress.',
        content: 'Sobhita Dhulipala royally ignores Ishaan Khattar at the ramp walk when they both appeared walking for the same designer and the fans connot get over this video and are claiming that they can watch it for more than 1000 times Recently the Made In Heaven 2 actress and Ishaan walked the ramp together in Delhi and their chemistry was zero and in fact the royal ignore by Sobhita on the ramp to Ishaan grabbed all the eyeballs nd many are lashing her over her attitude and others are loving it and calling her the pro. Sobhita looked HOT AF , but her ignore to Ishaan became the talk of the town and the video is going viral on the internet like a wildfire.',
        date: 'July 31, 2023',
      },
      {
        id: 8,
        genre: 'Bollywood',
        ref: 'https://www.bollywoodlife.com/news-gossip/nora-fatehi-takes-indirect-dig-at-actresses-who-date-big-actors-to-be-seen-says-she-was-asked-to-do-the-same-entertainment-news-2529316/',
        image: 'https://st1.bollywoodlife.com/wp-content/uploads/2023/07/kanagankaran-2.png?impolicy=Medium_Widthonly&w=1280&h=900',
        heading: 'Nora Fatehi takes indirect dig at actresses who date big actors to be seen, says she was asked to do the same',
        subheading: 'Watch the video of Nora Fatehi spilling the beans on the dark side of Bollywood, which will make you question the authenticity of the relationships in this industry.',
        content: 'Nora Fatehi is a self-made woman; she was initially laughed at, judged, and mocked, but she is now called a game changer and is going places with her talent. In her latest interview, Nora Fatehi talks about the dark side of Bollywood that we have witnessed in many films, including Heroine, which starred Kareena Kapoor Khan in the lead role. Now Nora reveals that she was asked many times by her PRs in Bollywood that she should date any big actor to be seen and how that will be helpful in her career. But Nora is proud of her accomplishment, which is not because of any other hero but herself. There are many netizens who think that she is taking an indirect dig at the actresses who are dating biggies and saying that the relationships in Bollywood are only for fame and publicity.',
        date: 'July 31, 2023',
      },
      {
        id: 9,
        genre: 'Bollywood',
        ref: 'https://www.bollywoodlife.com/news-gossip/kajol-calls-shah-rukh-khan-poor-guy-recalling-a-hilarious-incident-with-the-superstar-entertainment-news-2529283/',
        image: 'https://st1.bollywoodlife.com/wp-content/uploads/2023/07/kanagankaran-1.png?impolicy=Medium_Widthonly&w=1280&h=900',
        heading: 'Kajol calls Shah Rukh Khan ‘poor guy’ recalling a hilarious incident with the superstar',
        subheading: 'Kajol shared one of the incidents with Shah Rukh Khan while filming their blockbuster movie Dilwale Dulhania Le Jaayenge and called him a poor guy.',
        content: 'Kajol and Shah Rukh Khan share the greatest bond ever, and it\'s rare to see this kind of friendship. Kajol and SRK are buddies, and their bond is something that will make you want to have something similar like this. Both stars are super successful today and are doing absolutely great in their respective careers, and they have come a long way. In her recent interview, Kajol mentioned one incident that made her call SRK a poor guy at that time. Kajol shared one of her anecdotes from her blockbuster film Dilwale Dulhania Le Jaayenge along with Pathaan star, where she said that he got a frozen shoulder after he picked her up for a photoshoot for the said film. In an interaction with Curly Tales, Kajol sympathises with the Jawaan actor even now, and because of that, she feels extremely bad for him. ',
        date: ' July 31, 2023 ',
      },
      {
        id: 10,
        genre: 'Bollywood',
        ref: 'https://www.bollywoodlife.com/news-gossip/anurag-kashyap-raves-about-karan-johar-new-movie-rocky-aur-rani-kii-prem-kahaani-shares-highlight-of-ranveer-singh-alia-bhatt-film-entertainment-news-2528424/',
        image: 'https://www.bollywoodlife.com/news-gossip/anurag-kashyap-raves-about-karan-johar-new-movie-rocky-aur-rani-kii-prem-kahaani-shares-highlight-of-ranveer-singh-alia-bhatt-film-entertainment-news-2528424/',
        heading: 'Anurag Kashyap raves about Karan Johar new movie Rocky Aur Rani Kii Prem Kahaani; shares highlight of Ranveer Singh, Alia Bhatt film',
        subheading: 'Anurag Kashyap has heaped praises on Karan Johar directed Rocky Aur Rani Kii Prem Kahaani starring Ranveer Singh and Alia Bhatt. Here\'s what he has to say...',
        content: 'Rocky Aur Rani Kii Prem Kahaani is winning hearts all over. Karan Johar directed new movie stars Alia Bhatt as Rani and Ranveer Singh as Rocky with Jaya Bachchan, Shabana Azmi, Dharmendra and more in key roles. The opening day of Rocky Aur Rani Kii Prem Kahaani saw decent business and it\'s growing. A lot of celebrities have already praised the movie and now, Anurag Kashyap has also joined the list. He has penned a lengthy note expressing his thoughts on the new movie. ',
        date: 'July 30, 2023',
      },
      {
        id: 11,
        genre: 'Bollywood',
        ref: 'https://www.bollywoodlife.com/news-gossip/sonu-nigam-bhushan-kumar-hug-it-out-at-the-singers-birthday-bash-video-viral-entertainment-news-2528394/',
        image: 'https://www.bollywoodlife.com/news-gossip/sonu-nigam-bhushan-kumar-hug-it-out-at-the-singers-birthday-bash-video-viral-entertainment-news-2528394/',
        heading: 'Sonu Nigam, Bhushan Kumar hug it out at the singer\'s birthday bash',
        subheading: 'Sonu Nigam and Bhushan Kumar had a nasty spat a couple of months ago. But the water is under the bridge now. The T-Series head attended Sonu\'s birthday bash as well.',
        content: 'Sonu Nigam and Bhushan Kumar have a long-standing history. They have worked together for decades but about last year, it seems they had a fallout over something. Nasty allegations were made and Divya Khosla Kumar, Bhushan\'s wife had a nasty exchange over social media on the same. But it seems all is now well between Sonu Nigam and Bhushan Kumar of T-Series. In fact, today happens to be Sonu Nigam\'s birthday and a party was thrown which was attended by Kumar as well. The video is the talk of the town right now.',
        date: 'July 30, 2023',
      },
      {
        id: 12,
        genre: 'Bollywood',
        ref: 'https://www.bollywoodlife.com/news-gossip/double-ismart-sanjay-dutt-is-menacing-in-first-look-poster-fans-call-him-pan-indian-villain-entertainment-news-stst-2527798/',
        image: 'https://www.bollywoodlife.com/news-gossip/double-ismart-sanjay-dutt-is-menacing-in-first-look-poster-fans-call-him-pan-indian-villain-entertainment-news-stst-2527798/',
        heading: 'Double iSmart: Sanjay Dutt is menacing in first-look poster, fans call him ‘pan Indian villain’',
        subheading: 'Sanjay Dutt\'s first look poster for Double iSmart, captures him sporting a menacing gangster avatar. The poster was unveiled on his birthday, July 29.',
        content: 'Film director Puri Jagannadh’s 2019 action romance iSmart Shankar, starring Ram Pothineni was declared a hit upon its release. Now, after almost 4 years, Puri Jagannadh is back with the film’s sequel, titled Double iSmart, eyeing a release on March 8, 2024. But the upcoming sequel has a special twist. Besides Ram Pothineni reprising his role in Double iSmart, a Bollywood actor has been roped in as well. Any guesses? It is Sanjay Dutt. Yes, the good news comes with the makers dropping Dutt’s first look poster today, July 29. And needless to say, fans are gripped with excitement about his role in the film.',
        date: 'July 29, 2023',
      },
      {
        id: 13,
        genre: 'Bollywood',
        ref: 'https://www.bollywoodlife.com/news-gossip/kangana-ranaut-slams-karan-johar-for-wasting-rs-250-crores-on-rocky-aur-rani-kii-prem-kahaani-gives-this-advice-to-ranveer-singh-entertainment-news-2527734/',
        image: 'https://www.bollywoodlife.com/news-gossip/kangana-ranaut-slams-karan-johar-for-wasting-rs-250-crores-on-rocky-aur-rani-kii-prem-kahaani-gives-this-advice-to-ranveer-singh-entertainment-news-2527734/',
        heading: 'Kangana Ranaut slams Karan Johar for wasting Rs 250 crores on Rocky Aur Rani Kii Prem Kahaani; gives THIS advice to Ranveer Singh',
        subheading: 'Kangana Ranaut has taken to her social handle and slammed Karan Johar for making Rocky Aur Rani Kii Prem Kahaani. She also has given a piece of her mind to Ranveer Singh. Check out the Instagram stories of the actress below:',
        content: 'Rocky Aur Rani Kii Prem Kahaani starring Alia Bhatt and Ranveer Singh is in cinemas. It was released on 28th of July, Friday. The movie made a business of Rs 11.10 crores at the box office on its opening day. The numbers are not great but it\'s a decent box office for the movie. However, Kangana Ranaut does not think so. She has slammed the filmmaker, Karan Johar for making Rocky Aur Rani Kii Prem Kahaani. The actress has also given a piece of advice to Ranveer Singh. ',
        date: 'July 29, 2023',
      },
      {
        id: 14,
        genre: 'Bollywood',
        ref: 'https://www.bollywoodlife.com/news-gossip/sonu-nigam-issues-warning-against-imposter-woman-claiming-to-be-from-his-social-media-team-entertainment-news-stst-2527587/',
        image: 'https://www.bollywoodlife.com/news-gossip/sonu-nigam-issues-warning-against-imposter-woman-claiming-to-be-from-his-social-media-team-entertainment-news-stst-2527587/',
        heading: 'Sonu Nigam issues warning against imposter woman claiming to be from his social media team',
        subheading: 'Sonu Nigam\'s legal advisor, Ashish Joshi has ascertained that they will be taking appropriate legal measures to being the culprit into custody earliest by next week.',
        content: 'Sonu Nigam, one of the acclaimed Bollywood singers, will be celebrating his 50th birthday on July 30. Just a day ahead of the special occasion, the singer received an unpleasant surprise. Apparently, Sonu Nigam faced a scam pertaining to his social media handles. A woman has been sending text messages to the masses, calling herself to be from Sonu Nigam’s social media team. After learning about the scam going by his name, the singer has issued a warning to his fans who follow him on media platforms. An investigation is currently underway. ',
        date: 'July 29, 2023 ',
      },
      {
        id: 15,
        genre: 'Bollywood',
        ref: 'https://www.bollywoodlife.com/news-gossip/gadar-2-gaurav-chopra-on-the-sequel-of-an-iconic-film-you-will-not-feel-jabardasti-banaya-hai-exclusive-entertainment-news-2527182/',
        image: 'https://www.bollywoodlife.com/news-gossip/gadar-2-gaurav-chopra-on-the-sequel-of-an-iconic-film-you-will-not-feel-jabardasti-banaya-hai-exclusive-entertainment-news-2527182/',
        heading: 'Gadar 2: Gaurav Chopra on the sequel of an iconic film; \'You will not feel jabardasti banaya hai\'',
        subheading: 'Gadar 2 actor Gaurav Chopra assures that the film is not a \'jabardasti\' ka sequel. He also said that the story is moving organically and hence there will not be any trolling.',
        content: 'Sunny Deol and Ameesha Patel starrer Gadar 2 has been in the news since a long time. Gadar is an iconic film and the announcement of its sequeal has left everyone excited. Sunny Deol and Ameesha Patel will be returning as Tara Singh and Sakina in the film. The trailer of the film released recently and it has grabbed everyone\'s attention. The whole cast and crew of the film were present for the trailer launch.',
        date: 'July 28, 2023',
      },
      {
        id: 16,
        genre: 'Bollywood',
        ref: 'https://www.bollywoodlife.com/news-gossip/huma-qureshi-opens-up-on-being-body-shamed-dealing-with-negative-comments-entertainment-news-stst-2526273/',
        image: 'https://www.bollywoodlife.com/news-gossip/huma-qureshi-opens-up-on-being-body-shamed-dealing-with-negative-comments-entertainment-news-stst-2526273/',
        heading: 'Huma Qureshi opens up on being body shamed, dealing with negative comments',
        subheading: 'Recalling an incident when a film reviewer body-shamed her, Huma Qureshi opined that the masses do not review films now, they are more preoccupied with "being slanderous."',
        content: 'Huma Qureshi has always been a strong advocate of body positivity. Despite being trolled for her body weight and sartorial choices, she chooses to turn a deaf ear to the naysayers and live life on her own terms. But the incessant criticism sometimes does take a toll on her, revealed the Gangs of Wasseypur actress herself. In a heart-to-heart interaction with a media portal, Huma opened up about being body shamed, how it affected her at one point, and how she deals with such derogatory comments now.',
        date: 'July 28, 2023',
      },
      {
        id: 17,
        genre: 'Bollywood',
        ref: 'https://www.bollywoodlife.com/news-gossip/javed-akhtars-epic-reply-to-troll-who-tried-testing-his-knowledge-on-oppenheimer-goes-viral-entertainment-news-stst-2525838/',
        image: 'https://www.bollywoodlife.com/news-gossip/javed-akhtars-epic-reply-to-troll-who-tried-testing-his-knowledge-on-oppenheimer-goes-viral-entertainment-news-stst-2525838/',
        heading: 'Javed Akhtar\'s epic reply to troll who tried testing his knowledge on Oppenheimer goes viral',
        subheading: 'Christopher Nolan\'s biographical thriller Oppenheimer made its grand debut in India on July 21, and its opening day collection was an impressive Rs 14.5 crore.',
        content: 'Christopher Nolan\'s film Oppenheimer has been enjoying tremendous success at the box office in India. The theatres are filled to capacity, and fans are thoroughly engrossed in the gripping storyline. Even Bollywood celebrities have flocked to witness its brilliance on the silver screen. Many of these stars have taken to their social media platforms to share their reviews of the movie. Among them was the renowned screenwriter-lyricist, Javed Akhtar, who watched the film yesterday and shared a review on Twitter. Not only he gave a positive review but responded to a user who tried to test his knowledge.',
        date: 'July 27, 2023 ',
      },
      {
        id: 18,
        genre: 'Bollywood',
        ref: 'https://www.bollywoodlife.com/news-gossip/raghav-chadha-opens-up-on-how-his-life-took-a-turn-after-getting-engaged-to-parineeti-chopra-2524990/',
        image: 'https://st1.bollywoodlife.com/wp-content/uploads/2023/07/Parineeti-raghav-2.jpg?impolicy=Medium_Widthonly&w=1280&h=900',
        heading: 'Raghav Chadha opens up on how his life took a turn after getting engaged to Parineeti Chopra',
        subheading: 'Currently, Parineeti and Raghav are exploring various locations in Rajasthan to find the one that resonates with their vision and preferences. From the regal charm of Udaipur to the enchanting allure of Kishangarh, the couple is leaving no stone unturned in their quest for the perfect setting to exchange their vows.',
        content: 'Parineeti Chopra and Raghav Chadha are one of the newly engaged couples in T\'town and are all set to get married soon. Their pictures from the engagement, and later from the airport went viral for all the right reasons. The couple announced their engagement in May in New Delhi and is reportedly set to tie the knot later this year. Just like any other couple who are deeply in love, Raghav and Parineeti are spending quality time with each other. ',
        date: 'July 27, 2023',
      },
      {
        id: 19,
        genre: 'Bollywood',
        ref: 'https://www.bollywoodlife.com/news-gossip/bawaal-varun-dhawan-janhvi-kapoor-film-upsets-jewish-human-rights-ngo-pressure-on-ott-platform-to-take-down-the-film-entertainment-news-2524783/',
        image: 'https://st1.bollywoodlife.com/wp-content/uploads/2023/07/FotoJet-2023-07-27T092903.060.jpg?impolicy=Medium_Widthonly&w=1280&h=900',
        heading: 'Bawaal: Varun Dhawan, Janhvi Kapoor film upsets Jewish Human Rights NGO; pressure on OTT platform to take down the film?',
        subheading: 'Bawaal: Varun Dhawan, Janhvi Kapoor film makes Jewish centre for Holocaust victims upset; open letter to Prime Video to take down the movie',
        content: 'Varun Dhawan and Janhvi Kapoor\'s Bawaal left many netizens in shock after the climax scene drew inspiration with the condition of people at the Nazi death camp of Auschwitz. Netizens had been quick to call out the makers saying that comparing Hitler\'s genocide of Jews with the marital woes of a couple was tone deaf and downright offensive. The makers defended the movie saying that no one found it objectionable. In fact, many praised the film of social media saying it was an emotional affair. ',
        date: 'July 27, 2023',
      },
      {
        id: 20,
        genre: 'Bollywood',
        ref: 'https://www.bollywoodlife.com/news-gossip/decoding-how-kartik-aaryan-became-indias-own-gen-z-common-mans-superstar-entertainment-news-2523463/',
        image: 'https://st1.bollywoodlife.com/wp-content/uploads/2023/07/FotoJet-2023-07-26T140639.553.jpg?impolicy=Medium_Widthonly&w=1280&h=900',
        heading: 'Decoding how Kartik Aaryan became India\'s own Gen-Z \'Common man\'s superstar\'',
        subheading: 'As Kartik Aaryan gears up to receive the Rising Global Superstar of Indian Cinema Award, let us take a look at how deftly he carved his career in the industry',
        content: 'Kartik Aaryan has firmly established himself as one of the young superstars of the country. His track record at the box office is impeccable. Barring the odd Shehzada, all his films have recovered money. After the pandemic, he was one of the first stars to give a Rs 200 crore plus movie with Bhool Bhulaiyaa 2. Kartik Aaryan is soon going to be felicitated at the Indian Film Festival of Melbourne as the Rising Global Star. He said he is thrilled to get the invite from the Victorian Government. Kartik Aaryan has delivered a number of successful movies and is known as the common man\'s superstar. In today\'s BollywoodLife Specials, let us analyze his phenomenal growth in Bollywood.',
        date: 'July 26, 2023',
      },
      {
        id: 21,
        genre: 'Technology',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 22,
        genre: 'Technology',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 23,
        genre: 'Technology',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 24,
        genre: 'Technology',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 25,
        genre: 'Technology',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 26,
        genre: 'Technology',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 27,
        genre: 'Technology',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 28,
        genre: 'Technology',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 29,
        genre: 'Technology',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 30,
        genre: 'Technology',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 31,
        genre: 'Technology',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 32,
        genre: 'Technology',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 33,
        genre: 'Technology',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 34,
        genre: 'Technology',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 35,
        genre: 'Technology',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 36,
        genre: 'Technology',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 37,
        genre: 'Technology',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 38,
        genre: 'Technology',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 39,
        genre: 'Technology',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 40,
        genre: 'Technology',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 41,
        genre: 'Hollywood',
        ref: 'https://www.koimoi.com/box-office/barbie-beats-wonder-woman-being-the-highest-grossing-film-directed-by-a-female-director-is-just-less-than-100-million-away-from-entering-the-1-billion-club-to-surpass-captain-marvel/',
        image: 'https://static-koimoi.akamaized.net/wp-content/new-galleries/2023/08/barbie-box-office-margot-robbie-starrer-likely-to-enter-the-coveted-billion-dollar-club-before-monday-director-greta-gerwig-all-set-to-make-history-001.jpg',
        heading: 'Barbie Beats Wonder Woman Being The Highest Grossing Film Directed By A Female Director, Is Just Less Than $100 Million Away From Entering The $1 Billion Club To Surpass Captain Marvel',
        subheading: 'Greta Gerwig’s Barbie is all set to make history as it’s less than $100 million away from entering the coveted $1 billion club. Read on!',
        content: 'Greta Gerwig’s Barbie, starring Margot Robbie as the much-loved doll and Ryan Gosling as Ken, is unstoppable. The juggernaut of the bubblegum pink flick has taken the worldwide box office by storm and has smashed and made some records. And now, the musical fantasy will likely make more records by the time Monday is here! As reported by CNBC, Margot Robbie and Ryan Gosling-led Barbie has already collected $916.1 million and is expected to hit the coveted billion-dollar benchmark before Monday. Yes, the film needs less than $100 million to be part of the $1 billion club.',
        date: 'August 5, 2023',
      },
      {
        id: 42,
        genre: 'Hollywood',
        ref: 'https://www.koimoi.com/hollywood-news/christopher-nolan-holding-an-imax-65mm-camera-weighing-over-113-kg-over-cillian-murphy-in-this-bts-image-from-oppenheimer-has-caught-netizens-attention-one-says-i-would-be-so-terrif/',
        image: 'https://static-koimoi.akamaized.net/wp-content/new-galleries/2023/08/netizens-react-to-christopher-nolan-holding-an-imax-65mm-camera-weighing-over-113-kg-over-cillian-murphy-in-bts-image-from-oppenheimer-001.jpg',
        heading: 'Christopher Nolan Holding An IMAX 65mm Camera Weighing Over 113 Kg Over Cillian Murphy In This BTS Image From Oppenheimer Has Caught Netizens’ Attention, One Says “I Would Be So Terrified”',
        subheading: 'A behind-the-scenes photo from Oppenheimer sets ft. Christopher Nolan, Cillian Murphy, & a giant IMAX camera has caught netizens’ attention - read on',
        content: 'Christopher Nolan is among the most celebrated filmmakers of all time. He never fails to blow away the audience’s minds with his work and recently left everyone in awe of his art of filmmaking with Oppenheimer. The director did go the extra mile to bring the story of J Robert Oppenheimer, the father of the atomic bomb, along with Cillian Murphy. As the director has always been very particular about every scene in his films, he even hung an IMAX camera over Murphy during one scene, which made the netizens go crazy. Apart from Murphy, the movie also stars Emily Blunt, Matt Damon, Robert Downey Jr, Florence Pugh, Rami Malek and more. Despite its box office battle against Margot Robbie and Ryan Gosling’s Barbie, the movie has broken various records across the globe.',
        date: 'August 5, 2023',
      },
      {
        id: 43,
        genre: 'Hollywood',
        ref: 'https://www.koimoi.com/hollywood-news/selena-gomez-goes-on-yet-another-alleged-date-with-zayn-malik-in-los-angeles-netizens-react-why-does-sel-have-the-same-taste-as-both-of-the-hadid-sisters/',
        image: 'https://www.koimoi.com/hollywood-news/selena-gomez-goes-on-yet-another-alleged-date-with-zayn-malik-in-los-angeles-netizens-react-why-does-sel-have-the-same-taste-as-both-of-the-hadid-sisters/',
        heading: 'Selena Gomez Goes On Yet Another Alleged Date With Zayn Malik In Los Angeles? Netizens React “Why Does Sel Have The Same Taste As Both Of The Hadid Sisters…”',
        subheading: 'Amid romance rumours, Selena Gomez goes out on an alleged date with Zayn Malik in Los Angeles. Find out the truth below.',
        content: 'Selena Gomez is currently on a roll on social media and sharing reels and pictures of herself on TikTok and Instagram, treating her fans time and again. The singer is also making alleged romance rumours with Zayn Malik, and on to the series of new events, new reports state that both Sel and Zayn reportedly went on an alleged date in Los Angeles. Netizens are now reacting to the reports on social media, and scroll below to read the scoop. Selena and Zayn both have a massive fan following on social media, with over 427 million and 50 million followers on Instagram. While ,there hasn’t been an official confirmation from both stars, but they have been spotted a few times together, according to reports.',
        date: 'August 5, 2023',
      },
      {
        id: 44,
        genre: 'Hollywood',
        ref: 'https://www.koimoi.com/hollywood-news/dc-gets-slammed-once-again-for-retaining-gal-gadots-wonder-woman-but-axing-henry-cavills-superman-one-says-it-should-be-a-felony/',
        image: 'https://www.koimoi.com/hollywood-news/dc-gets-slammed-once-again-for-retaining-gal-gadots-wonder-woman-but-axing-henry-cavills-superman-one-says-it-should-be-a-felony/',
        heading: 'DC Gets Slammed Once Again For Retaining Gal Gadot’s Wonder Woman But Axing Henry Cavill’s Superman, One Says “It Should Be A Felony”',
        subheading: 'DC fans are furious over the new changes as James Gunn decides to keep Gal Gadot in the roster but kicks out Henry Cavill. Read on for more!',
        content: 'The DC Extended Universe has undergone a complete makeover since James Gunn and Peter Safran took over. The first significant change was letting go of Henry Cavill as Superman, whom the fans adored. However, the studio did not hesitate to retain the scandalous Ezra Miller as The Flash. In recent news, we learned that Gal Gadot will indeed be returning as Wonder Woman for her third solo outing, and the fans are fuming in rage. James Gunn is chopping down trees left, right, and center and is not willing to compromise with his plans at all. According to him, Cavill, whose performance as Clark Kent received endless praise, did not fit into his plans. But Gal Gadot is not going anywhere. Initially, the ‘Guardians of the Galaxy’ director scrapped the script curated by Patty Jenkins, ensuring her departure from this venture.',
        date: 'August 5, 2023',
      },
      {
        id: 45,
        genre: 'Hollywood',
        ref: 'https://www.koimoi.com/hollywood-news/when-al-pacino-hinted-at-bad-blood-between-him-christopher-nolan-revealing-why-oppenheimer-director-possibly-didnt-offer-him-any-film-post-2002s-insomnia/',
        image: 'https://www.koimoi.com/hollywood-news/when-al-pacino-hinted-at-bad-blood-between-him-christopher-nolan-revealing-why-oppenheimer-director-possibly-didnt-offer-him-any-film-post-2002s-insomnia/',
        heading: 'When Al Pacino Hinted At Bad Blood Between Him & Christopher Nolan, Revealing Why Oppenheimer Director Possibly Didn’t Offer Him Any Film Post 2002’s Insomnia',
        subheading: '\'Godfather\' actor Al Pacino and the \'Oppenheimer\' director Christopher Nolan - might never work again and here\'s why.',
        content: 'Christopher Nolan is currently enjoying the massive success of ‘Oppenheimer’ starring Cillian Murphy, Robert Downey Jr, Florence Pugh, and more. The director has been delivering quality content since day one, which has put him on a pedestal. Now, when you become great, you work with greats, right? The same was the case with Nolan as he collaborated with the legendary Al Pacino in 2002 for a movie called ‘Insomnia’. If you ever wondered why they did not work together again, let us help you find the answer. Al Pacino has touched and turned everything into gold throughout this career. One such movie was ‘Insomnia’ which was directed by Nolan. On a budget of $46 Million, the movie grossed over $116 million, making it a success. So why didn’t these two shake hands for another flick? Al Pacino once revealed the reason behind this lesser-known beef.',
        date: 'August 5, 2023',
      },
      {
        id: 46,
        genre: 'Hollywood',
        ref: 'https://www.koimoi.com/hollywood-news/zack-snyders-justice-league-sequel-had-plans-of-making-this-villain-a-big-baddy-of-the-dc-universe/',
        image: 'https://www.koimoi.com/hollywood-news/zack-snyders-justice-league-sequel-had-plans-of-making-this-villain-a-big-baddy-of-the-dc-universe/',
        heading: 'Zack Snyder’s Justice League Sequel Had Plans Of Making This Villain A “Big Baddy Of The DC Universe”',
        subheading: 'New details have now revealed Zack Snyder had plans of carrying the DCEU even further with an entirely new villain. Read on for more!',
        content: 'DCEU kicked off in the right direction with Zack Snyder behind the wheel. However, not every great thing comes to fruition. The same thing happened with the Snydervesrse, which was a detailed plan of your favourite DC superheroes going against the most powerful supervillains. It all came crashing down in 2016 when Justice League dropped and the movie was slammed by almost everyone. Now, a DCEU creative has revealed the big plans they had for the Justice League Sequel. There was going to be a Flash villain! Snyder has time and again explained that he had plans of creating an Avengers: Endgame-esque meet-up for the DCEU superheroes. But according to the fans, his vision was not taken into consideration, following which he stepped out. But that doesn’t mean we cannot know what they had planned. Let’s take a look.',
        date: 'August 5, 2023',
      },
      {
        id: 47,
        genre: 'Hollywood',
        ref: 'https://www.koimoi.com/hollywood-news/did-dwayne-johnson-blame-james-gunn-peter-safran-taking-dcs-control-in-hands-for-the-mega-failure-of-his-black-adam-by-saying-it-got-caught-in-a-vortex-of-new-leadership/',
        image: 'https://www.koimoi.com/hollywood-news/did-dwayne-johnson-blame-james-gunn-peter-safran-taking-dcs-control-in-hands-for-the-mega-failure-of-his-black-adam-by-saying-it-got-caught-in-a-vortex-of-new-leadership/',
        heading: 'Did Dwayne Johnson Blame James Gunn & Peter Safran Taking DC’s Control In Hands For ‘Black Adam’ Franchise Getting Scrapped By Saying “It Got Caught In A Vortex Of New Leadership”?',
        subheading: 'Dwayne Johnson reflects on his controversial DC film Black Adam & what went wrong with it. Here\'s what he has to say about it!',
        content: 'The DC Universe has been going through huge changes, and it began with the appointment of James Gunn and Peter Safran as the new heads. Dwayne Johnson, who made his DCEU debut with Black Adam, got pulled into many controversies, especially for bringing back Henry Cavill’s Superman. Now, the actor has once again reflected on that time and what went wrong. Scroll below to get the deets. Johnson’s superhero film came out in 2022, and it received mixed reviews from the audience, but out and out, it was The Rock’s film, and he did it well to promote it, but things did not pan out in his favour. But bringing back Cavill for the post-credit sure gave hope among fans, only to get shattered soon after Gunn and Safran took over the DCU.',
        date: 'August 5, 2023',
        name: 'Hrishabh'
      },
      {
        id: 48,
        genre: 'Hollywood',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        content: '',
        date: '',
      },
      {
        id: 49,
        genre: 'Hollywood',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        content: '',
        date: '',
      },
      {
        id: 50,
        genre: 'Hollywood',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        content: '',
        date: '',
      },
      {
        id: 51,
        genre: 'Hollywood',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        content: '',
        date: '',
      },
      {
        id: 52,
        genre: 'Hollywood',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        content: '',
        date: '',
      },
      {
        id: 53,
        genre: 'Hollywood',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        content: '',
        date: '',
      },
      {
        id: 54,
        genre: 'Hollywood',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        content: '',
        date: '',
      },
      {
        id: 55,
        genre: 'Hollywood',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        content: '',
        date: '',
      },
      {
        id: 56,
        genre: 'Hollywood',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        content: '',
        date: '',
      },
      {
        id: 57,
        genre: 'Hollywood',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        content: '',
        date: '',
      },
      {
        id: 58,
        genre: 'Hollywood',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        content: '',
        date: '',
      },
      {
        id: 59,
        genre: 'Hollywood',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        content: '',
        date: '',
      },
      {
        id: 60,
        genre: 'Hollywood',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        content: '',
        date: '',
      },
      {
        id: 61,
        genre: 'Fitness',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 62,
        genre: 'Fitness',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 63,
        genre: 'Fitness',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 64,
        genre: 'Fitness',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 65,
        genre: 'Fitness',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 66,
        genre: 'Fitness',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 67,
        genre: 'Fitness',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 68,
        genre: 'Fitness',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 69,
        genre: 'Fitness',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 70,
        genre: 'Fitness',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 71,
        genre: 'Fitness',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 72,
        genre: 'Fitness',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 73,
        genre: 'Fitness',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 74,
        genre: 'Fitness',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 75,
        genre: 'Fitness',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 76,
        genre: 'Fitness',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 77,
        genre: 'Fitness',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 78,
        genre: 'Fitness',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 79,
        genre: 'Fitness',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 80,
        genre: 'Fitness',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 81,
        genre: 'Food',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 82,
        genre: 'Food',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 83,
        genre: 'Food',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 84,
        genre: 'Food',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 85,
        genre: 'Food',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 86,
        genre: 'Food',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 87,
        genre: 'Food',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 88,
        genre: 'Food',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 89,
        genre: 'Food',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 90,
        genre: 'Food',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 91,
        genre: 'Food',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 92,
        genre: 'Food',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 93,
        genre: 'Food',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 94,
        genre: 'Food',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 95,
        genre: 'Food',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 96,
        genre: 'Food',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        date: '',
      },
      {
        id: 97,
        genre: 'Food',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        content: '',
        date: '',
      },
      {
        id: 98,
        genre: 'Food',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        content: '',
        date: '',
      },
      {
        id: 99,
        genre: 'Food',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        content: '',
        date: '',
      },
      {
        id: 100,
        genre: 'Food',
        ref: '',
        image: '',
        heading: '',
        subheading: '',
        content: '',
        date: '',
      },
    ])
  return (
    <Store.Provider value={Data}>
        {props.children}
    </Store.Provider>
  )
}

export default DataStorage